name: Publish Angular Library to npm

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.1.0, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Set your Node.js version
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci  # Installs dependencies based on package-lock.json

      - name: Build Angular Library
        run: npx ng build shared  # Build the Angular library in the "projects/shared" folder

      - name: Publish to npm
        run: |
          cd dist/shared  # Navigate to the dist folder of your library
          npm publish --access public  # Publish to npm as a public package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CEPH_NPM_TOKEN }}  # Use the NPM token stored in GitHub Secrets

